### PR TITLE
Rename config files

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
Renames the model and data config files as per the defaults expected by scivision

### CODE REVIEW

**Comment by edwardchalstrey1** [comment]
@acocac please could you review?

**Review by acocac — APPROVED** [review]
The changes look good to me.

**Comment by edwardchalstrey1** [comment]
> The changes look good to me.

@acocac I don't have the power to merge, can you do it?

**Comment by acocac** [comment]
@edwardchalstrey1 nope, it says there are conflicts that must be resolved.

**Comment by edwardchalstrey1** [comment]
> @edwardchalstrey1 nope, it says there are conflicts that must be resolved.

I can't view the conflict, what does it say?

**Comment by acocac** [comment]
It says the conflicts are too complex to solve in the web editor. It suggest using the command line to resolve conflicts before continuing.

**Comment by edwardchalstrey1** [comment]
> It says the conflicts are too complex to solve in the web editor. It suggest using the command line to resolve conflicts before continuing.

@acocac ok I fixed it

**Review by acocac — APPROVED** [review]

**Pull request merged**
